# Generated by Django 5.0.3 on 2024-04-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0002_material_productmaterial_product_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.AddField(
            model_name='product',
            name='product_material',
            field=models.ManyToManyField(through='simpleapp.ProductMaterial', to='simpleapp.material'),
        ),
    ]
